[package]
name = "e2mc-test-rs"
version = "0.1.0"
edition = "2018"

[dependencies]
steven_shared = { git = "https://github.com/iceiix/stevenarella", rev = "1a9e8d40" }
steven_blocks = { git = "https://github.com/iceiix/stevenarella", rev = "1a9e8d40" }
